
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kind.meln5674
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kind.meln5674
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kind.meln5674
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - 'apps'
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - get
  - create
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
